### ISSUE TITLE
RFC: Migrating release process to Twister and `east pack` command

### ISSUE THREAD

**Issue by MarkoSagadin** [IRNAS/irnas-east-software#125]
## Context

`east release` command and `east.yaml` became more and more unsuitable as the Zephyr project kept
introducing newer build system concepts (for example: sysbuild, shields, snippets).

Instead of trying to keep up in terms of functionality in the East's codebase, it is more pragmatic
to reuse what Zephyr already offers and try to build on top of it.

I have recently opened an [issue](https://github.com/zephyrproject-rtos/zephyr/issues/86720) on the
Zephyr's GitHub to start the discussion on the topic of adding a release process generation tool to
the `west command` or `west twister`.

Since there wasn't much feedback from the community I decided that the way to go was to add
`east pack` command that will do something like I suggested in the linked issue:

> As a separate west command that processes the twister-out folder and generates the final release
> directory.

This issue serves as a place for discussion on how this new `east pack` command should be
implemented and how configurable it should be.

## High-level ideas:

- `east pack` requires that `east twister` / `west twister` command was run first, as it requires
  `twister-out` as an input.
- It shouldn't be required that Twister is invoked with some specific flags for the `east pack` to
  work.
- The selection of build artifacts should be configurable since that is pretty much application-specific. Some projects need the final application hex file, in other cases they need
  `app_update.bin`, `dfu_application.zip`, etc.
- The resulting folder structure should be sensible and understandable by technical non-Zephyr
  users.

## Configurability

`east pack` should be configurable via `east.yaml` file.

Some rules about the configuration format:

- `pack.projects.<project_name>.artifacts` - list of artifacts that should be included in the
  release folder.
- `pack.projects.<project_name>.artifacts.<artifact_name>` - path to the artifact file (not dir). It
  must be relative to the build folder
- `$APP_DIR` - special variable that will be replaced with the path to the application directory
  that is found in the generated build folder. Since that path is always different for each project and
  it can depend on whether the sysbuild is used or not, it is practical to hardcode it in the
  `east.yaml`.

```yaml
pack:
  projects:
    app.prod:
      artifacts:
        - $APP_DIR/zephyr.hex
        - $APP_DIR/zephyr.elf
        - $APP_DIR/mcuboot.hex
        - dfu_application.zip
    app.rtt:
      artifacts:
        - $APP_DIR/zephyr.hex
        - dfu_application.zip
```

To avoid duplication of the same artifacts for multiple projects, there should be a way to define
common artifacts for all projects. This can be done by adding a `pack.artifacts` key to the
`east.yaml`.

```yaml
pack:
  artifacts:
    - $APP_DIR/zephyr.hex
    - dfu_application.zip
  projects:
    app.prod:
      artifacts:
        - $APP_DIR/zephyr.elf
        - $APP_DIR/mcuboot.hex
```

- `pack.artifacts` - list of artifacts that should be included in the release folder for all
  projects. This is useful for artifacts that are common for all projects, like
  `dfu_application.zip` or `mcuboot.hey`.
- `pack.projects.<project_name>.artifacts` extends the `pack.artifacts` list.

From above follows:

- Each project needs to have a list of artifacts that should be gathered. It gets that list either
  by extending the common artifacts list or by defining its own list. If it doesn't have a list that
  is considered a configuration error and `east pack` should fail.

## Generated folder structure

TODO: This needs to be expanded.

## Definition of Done

TODO: This needs to be expanded.

## Related issues

Once this is implemented the following issues can be closed:
- #123
- #122
- #48

**Comment by TjazVracko** [comment]
![Image](https://github.com/user-attachments/assets/69064c96-25fd-4a83-a062-bb6be3d089f6)

This is not clear to me.

Does a project-specific list of artifacts overwrite the common list, or does it append to it?

So, for your example, will the artifacts for `app.prod` be `zephyr.hex, dfu_application.zip, zephyr.elf, mcuboot.hex` or just  `zephyr.elf, mcuboot.hex` ?

----------------------

What I would want is, for example:

Imagine I have 3 test cases for `app`: `app.dev`, `app.prod` and `app.rtt` 

`east.yml` looks like this:

```
pack:
  artifacts:
    - $APP_DIR/zephyr.hex
    - dfu_application.zip
  projects:
    - app.prod:
      artifacts:
        - $APP_DIR/zephyr.elf
        - $APP_DIR/mcuboot.hex
   - app.dev
```

(not sure if the yaml above is valid)


`east pack` gives me:
1. For `app.prod`: `zephyr.hex, dfu_application.zip, zephyr.elf, mcuboot.hex`
2. For `app.dev`: `zephyr.hex, dfu_application.zip`
3. For `app.rtt`: Nothing, this is not a release target. I don't even wa't a `app.rtt` folder.


----------------------

The filtering will be done with the `release` tag anyway, no?
What do you think?

**Comment by MarkoSagadin** [comment]
> Does a project-specific list of artifacts overwrite the common list, or does it append to it?

Append to it.

> So, for your example, will the artifacts for app.prod be zephyr.hex, dfu_application.zip, zephyr.elf, mcuboot.hex or just zephyr.elf, mcuboot.hex ?

First case.

I though about this, it also makes sense to have something like `pack.projects.<project_name>.overwrite_artifacts` field, that overwrites the common list instead of appending to it.

> Imagine I have 3 test cases for app: app.dev, app.prod and app.rtt
>
> east pack gives me:
>
>    For app.prod: zephyr.hex, dfu_application.zip, zephyr.elf, mcuboot.hex
>    For app.dev: zephyr.hex, dfu_application.zip
>    For app.rtt: Nothing, this is not a release target. I don't even wa't a app.rtt folder.

To get that from the `east pack` you would need to:
1. Not add `release` tag to the `app.rtt` in the `sample.yaml`
2. Have below `east.yaml`:

```yaml
pack:
  artifacts:
    - $APP_DIR/zephyr.hex
    - dfu_application.zip
  projects:
    - app.prod:
      artifacts:
        - $APP_DIR/zephyr.elf
        - $APP_DIR/mcuboot.hex
```

You were close, my current idea is that there is no need to explicitly list a project if there is already common `pack.artifacts` list that defines the list of artifacts for it.

What am I envisioning with this setup:
* If you have `pack.artifacts` set up that you are happy with, adding a new configuration to the packing should require to just add a `release` tag to the `sample.yaml`
* If the configuration that you are adding is somewhat special then you also need to do extra work to specify it in the `east.yaml`.

**Comment by eva-cerncic** [comment]
I agree with the idea, this concept looks very nice! 

I have a question regarding other files that one might want to include in the release that are not directly related to build artifacts, such as Python or JS scripts, for example (TTN parser comes to my mind there). Is there a way to include those in the final release folder as well to avoid manual adding and renaming, which is, as we all know, time-consuming and prone to errors?

**Comment by eva-cerncic** [comment]
@TjazVracko renaming was what I meant, I did not write it clearly enough, thank you. :)

**Comment by TjazVracko** [comment]
@MarkoSagadin 

#82 can also possibly be closed after this. With twister, you can add a flag to only rebuild the failures, so I can just copy the `make release` twister call and add that flag.

**Comment by TjazVracko** [comment]
> The current east release only does renaming for the first one. If you want renaming to be done in some automated way, you need to write a script that will parse the output of git describe and do the renaming. That is not ideal, so I imagine that is either done manually or not at all.
> 
> If we would want to implement such naming in the east pack command then additional files that need to be part of the release should somehow be listed in the east.yml, that way east can know about them, move them and rename them.

Something like:

```yaml
pack:
  extra:
    - scripts/decoder/ttn_decoder.js
    - scripts/updater/updater.zip
    - ...
```

And the makefile something like:

```make
release:
    east twister blablabla

pre-package:
    # create updater.zip
    ./scripts/updater/release_it.py
    east pack
```

I guess this could work.

---------------------------

I feel like this is "feature creep" already.

If CI would put the current version being released into an ENV var, I could do all of this in the makefile myself.
Like this:

```make
release:
    east twister blablabla

pre-package:
     mkdir -p artefacts
   
    # create updater.zip
    ./scripts/updater/release_it.py
    # copy stuff to the artefacts folder and add the version to the name
    cp scripts/updater/updater.zip artefacts/updater_{$VERSION}.zip
    cp scripts/decoder/ttn_decoder.js artefacts/ttn_decoder_{$VERSION}.js
    
   # I assume eat pack puts the zip in the artefacts folder already, If not, copy it
    east pack
   # cp packed/*.zip artefacts
```
