### ISSUE TITLE
BUG - twister filtered test case in twister.json

### ISSUE THREAD

**Issue by klancarLuka** [IRNAS/irnas-east-software#152]
#### Describe the bug

When running twister with older NCS (v2.2.0), twister adds platform incompatible tests as `status:filtered` to `twister-out/twister.json`.

#### Firmware/software version

Zephyr version v3.2.99-ncs1
NCS vesrion 2.2.0

#### Steps to reproduce

zephyr/scripts/twister -T tests/sample_test -p native_posix

testcase.yaml:

```
tests:
  tests.sample_test.posix:
    # Set of platforms that this test case can be run on.
    platform_allow: native_posix
    harness: ztest
    # Only build the test, do not run it
    # build_only: True
    extra_configs:
      # Disable fancy test, otherwise stdout parsing does not work.
      - CONFIG_FANCY_ZTEST=n
  tests.sample_test.target:
    # Set of platforms that this test case can be run on.
    platform_allow: nrf52dk_nrf52832 nrf52840dk_nrf52840
    harness: ztest
    # Only build the test, do not run it
    # build_only: True
    extra_configs:
      # Disable fancy test, otherwise stdout parsing does not work.
      - CONFIG_FANCY_ZTEST=n
      # See https://github.com/zephyrproject-rtos/zephyr/issues/39216 to learn
      # why this flag is needed here.
      - CONFIG_NULL_POINTER_EXCEPTION_DETECTION_NONE=y
```

  tests.sample_test.target gets added as filtered even though it was skipped.

**Comment by TjazVracko** [comment]
@klancarLuka east.yml also pls.

**Comment by klancarLuka** [comment]
.yml files are not allowed to be uploaded by Github, so I'll post the contents here:

```yml
apps:
  - name: open-collar
    west-boards:
      - rhinoedge_nrf52840
      - rangeredge_nrf52840
      - rhinopuck_nrf52840
      - rhinopuck35_nrf52840
      - collaredge_nrf52840
      - freeedge_nrf52840

    build-types:
      - type: debug
        conf-files:
          - debug.conf
          - disable_mcuboot.conf
      - type: log
        conf-files:
          - log_rtt.conf
      - type: prov
        conf-files:
          - prov.conf

samples:
  - name: lr11xx-transceiver-update
    west-boards:
      - rhinoedge_nrf52840
      - rangeredge_nrf52840
      - rhinopuck_nrf52840
      - rhinopuck35_nrf52840
      - collaredge_nrf52840
      - freeedge_nrf52840
```
