### ISSUE TITLE
BUG - Unable to inherit the release build type from a sample

### ISSUE THREAD

**Issue by TjazVracko** [IRNAS/irnas-east-software#47]
**Describe the bug**
When building a sample with inherited build types, that "release type" can not be named in `east.yml`.

**Firmware/Software Version**
0.6.2

**To Reproduce**
Create east.yml something like:
```yaml
apps:
  - name: nrf52_app
    west-boards:
      - custom_nrf52840dk
      - nrf52840dk_nrf52840
    build-types:
      - type: debug
        conf-files:
          - debug.conf
      - type: uart
        conf-files:
          - debug.conf
          - uart.conf

  - name: nrf91_app
    west-boards:
      - nrf9160dk_nrf9160_ns

    build-types:
      - type: debug
        conf-files:
          - debug.conf

samples:
  - name: settings
    west-boards:
      - custom_nrf52840dk
    inherit-build-type:
      app: nrf52_app
      build-type: release # <---- offending line

```

Build the sample: 
```
east build -b custom_nrf52840dk;

Sample settings is trying to inherit from a non-existing build-type 
release.


```

**Additional context**

I would consider the option that a sample could be built for any of the build types, same as the app.
