### ISSUE TITLE
Feature: Refactor build-types for apps and samples 

### ISSUE THREAD

**Issue by MarkoSagadin** [IRNAS/irnas-east-software#48]
## Context

Build type system does not cover one of the possible project configurations that came up in practical development. Due to that usage of build types is uncomfortable/non-convenient.

## Problematic setup

Project is setup to build for two different boards:
* some regular board, such as `nrf52840dk_nrf52840`
* `native_posix` board, suitable for running on the development machine

For `nrf52840dk_nrf52840`   board we want to have a `dev`  build type, which uses debug KConfig options and RTT Kconfig options (RTT is used as logging and shell back-end), and `debug` build type, which used debug KConfig options.

`native_posix` board only needs `debug` build type.

`east.yml` for such setup would look something like this: 

```yaml
apps:
  - name: example_app
    west-boards:
      - nrf52840dk_nrf52840
      - native_posix

    build-types:
      - type: dev
        conf-files:
          - debug.conf
          - rtt.conf

      - type: debug
        conf-files:
          - debug.conf
```

#### The problem

With above config  `east release` builds every possible west-board/build-type combination. This is not okay as `native_posix` does not support RTT, so you get a bunch of warnings when compiling for this combination.

Basically, all possible build-types are not suitable for all west-boards.

## Solution

Add a new `combinations` key, where each west-board defines its own list of possible build-types.
There can be one or more west-boards, for each combination.

That way we can avoid the above situation.

In that case the `east.yml` should support something like this:

```yaml

apps:
  - name: example_app
    combinations:
      - west-boards: 
        - nrf52840dk_nrf52840
        - nrf52dk_nrf52832
        build-types:
        - type: dev
          conf-files:
            - debug.conf
            - rtt.conf
        - type: debug
          conf-files:
            - debug.conf
         
      - west-boards: 
        - native_posix
        build-types:
        - type: debug
          conf-files:
            - debug.conf
   
```
